version: "3.9"

services:
  timelapse-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timelapse-worker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp           # optional persistence

    # GPU example (commented)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]