version: "3.9"

services:
  heic-converter:
    build: .
    volumes:
      - ./input:/data/in:ro
      - ./output:/data/out
    environment:
      SOURCE_DIR: /data/in
      OUTPUT_DIR: /data/out
    restart: on-failure